### PR TITLE
Respect Plone external url

### PR DESCRIPTION
**Pull request by rodfersou**
closes https://github.com/simplesconsultoria/sc.recipe.staticresources/issues/44

### CODE REVIEW

**Comment by hvelarde** [comment]
can you check why tests are failing?

**Comment by rodfersou** [comment]
```python
Version and requirements information containing pycodestyle:
  [versions] constraint on pycodestyle: 2.3.1
  Requirement of flake8-todo: pycodestyle<3.0.0,>=2.0.0
  Requirement of flake8-print: pycodestyle
  Requirement of flake8-debugger: pycodestyle
  Requirement of flake8>=2.4.0: pycodestyle<2.5.0,>=2.4.0
  Requirement of flake8: pycodestyle<2.5.0,>=2.4.0
  Requirement of flake8>=1.5: pycodestyle<2.5.0,>=2.4.0
  Requirement of flake8>=3.0: pycodestyle<2.5.0,>=2.4.0
  Requirement of flake8>=3.2.1: pycodestyle<2.5.0,>=2.4.0
  Requirement of flake8>=3.0.0: pycodestyle<2.5.0,>=2.4.0
  Requirement of flake8<4.0.0,>=2: pycodestyle<2.5.0,>=2.4.0
While:
  Installing.
  Getting section code-analysis.
  Initializing section code-analysis.
  Installing recipe plone.recipe.codeanalysis[recommended].
Error: The requirement ('pycodestyle<2.5.0,>=2.4.0') is not allowed by your [versions] constraint (2.3.1)
```

**Comment by rodfersou** [comment]
need to pin something..

**Comment by rodfersou** [comment]
@hvelarde I try to fix it.. no success, can you help?

**Pull request merged**
